#!/bin/sh
yum install boost-date-time -y
yum install boost-filesystem -y
yum install boost-program-options -y
yum install boost-regex -y
yum install boost-system -y
yum install boost-thread -y
yum install bzip2 -y 
yum install bzip2-libs -y
yum install libicu -y
yum install libjpeg-turbo -y
yum install libmng -y
yum install qt -y
yum install qt-settings -y
yum install qt-x11 -y
yum install xerces-c -y
yum install xmlrpc-c -y
yum install xmlrpc-c-c++ -y
yum install xmlrpc-c-client -y
yum install xmlrpc-c-client++ -y